# Generated by Django 5.2.3 on 2025-06-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="https://res.cloudinary.com/dbdqfgqti/image/upload/v1751310469/default.jpg",
                upload_to="profile_pics",
            ),
        ),
    ]
