# Generated by Django 5.2.3 on 2025-06-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_posted",
            new_name="Date_Posted",
        ),
    ]
